apiVersion: v1
kind: Service
metadata:
  name: apachewww
spec:
  selector:
    app: apachewww
  ports:
  - protocol: TCP
    port: 80       # Port exposed by the service
    targetPort: 80 # Apache container's port
    nodePort: 31000  # Port exposed on Minikube node
  type: NodePort
